export default [
    {
        code:100,
        remark:'获取数据成功'
    },{
        code:102,
        remark:'该账户不存在'
    },{
        code:103,
        remark:'密码只能为6-20位的字母、数字、字符组合(!@#$%^&*()-=_+,.<>/-)'
    },{
        code:128,
        remark:'交易金额精度超出范围'
    },{
        code:126,
        remark:'交易金额必须大于0'
    },{
        code:104,
        remark:'正在同步区块，无法转账'
    },{
        code:105,
        remark:'发送方账户不存在'
    },{
        code:201,
        remark:'接收账户未产生交易，请提供钱包公钥'
    },{
        code:301,
        remark:'密码错误'
    },{
        code:401,
        remark:'钱包地址与公钥不一致'
    },{
        code:106,
        remark:'可用余额不足'
    },{
        code:129,
        remark:'发送方ptn余额不足'
    },{
        code:200,
        remark:'转账申请已提交'
    }
]